package praticalexam;

public class ConstructorQuestions {

    //A CONSTRUCTOR cannot be FINAL, STATIC OR ABSTRACT !
    //THE FUNCTION OF CONSTRUCTOR IS TO CREATE A INSTANCE OF OBJECTS

    //CONSTRUCTOR CAN ACCESS STATIC MEMBERS

    //SUPERCLASS MUST HAVE A DEFAULT CONSTRUCTOR
    //IF NOT COMPILATIONS FAIL!

}